services:
  - type: web
    name: focusflow
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn gorev_sistemi.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: gorev_sistemi.settings # Ana settings.py dosyanızın bulunduğu dizin ve dosya adı
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
