# Generated by Django 5.2.1 on 2026-05-05 11:13

from django.db import migrations, models


def seed_task_status(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    for task in Task.objects.all():
        task.status = "Done" if task.completed else "To Do"
        task.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_assigned_to_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Blocked', 'Blocked'), ('Done', 'Done')], default='To Do', max_length=20),
        ),
        migrations.RunPython(seed_task_status, migrations.RunPython.noop),
    ]
